version: '3.8'

services:
  redis:
    image: redis:latest

    container_name: redis

    ports:
      - "6379:6379"

    networks:
      - botnet

    restart: always

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5

  bot:
    build: .

    container_name: telegram_bot

    restart: always

    env_file:
      - .env

    depends_on:
      redis:
        condition: service_healthy

    networks:
      - botnet

networks:
  botnet:
    driver: bridge
